// Generated by CoffeeScript 1.9.3
(function() {
  var data, getData, onData;

  data = [];

  onData = function() {
    var S, line, raw, target, valueName;
    raw = JSON.parse(this.responseText);
    data.push(raw["data"][0]);
    target = "target";
    valueName = "value";
    S = new Spark();
    line = S.spark(data, valueName);
    return document.getElementById(target).innerHTML = line;
  };

  getData = function() {
    var method, request, url;
    method = "GET";
    url = "data.php";
    request = new XMLHttpRequest();
    request.addEventListener("load", onData);
    request.open(method, url);
    request.send(null);
    return setTimeout(getData, 300);
  };

  document.addEventListener("DOMContentLoaded", getData);

}).call(this);

//# sourceMappingURL=main.js.map
