// Generated by CoffeeScript 1.9.3
(function() {
  this.Spark = (function() {
    var CLOSE, OPEN, PREFIX, SUFFIX;

    OPEN = "<svg width=\"100\" height=\"50\" viewPort=\"0 0 100 50\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">";

    PREFIX = "<polyline  points=\"";

    SUFFIX = "\" style=\"stroke:#006600;\" fill=\"none\" />";

    CLOSE = "</svg>";

    function Spark() {
      console.log("creating a spark factory");
    }

    Spark.prototype.spark = function(data, valueName) {
      var final, i, index, item, len, list, output, x;
      list = [];
      console.log("creating a spark from data");
      for (index = i = 0, len = data.length; i < len; index = ++i) {
        item = data[index];
        x = index * 10;
        list.push(x + "," + item[valueName]);
      }
      output = list.join(" ");
      final = OPEN + PREFIX + output + SUFFIX + CLOSE;
      console.log(final);
      return final;
    };

    return Spark;

  })();

}).call(this);

//# sourceMappingURL=spark.js.map
